# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa2ddc868dc0a8693b3fe34bda3a66cdc09af2c36abd9bff7517d1f7a685681826c4a5fd11f3be90c9472d9b715ede728cc45cd5858014d2e74bd2dd6f3084f5

test:
  secret_key_base: e49e553d05b40f30a5b1412520f235f37659e183165104a97eac994fbf84bdd49f41f1a47997ed3e7bbb7506206089b40fb29e63e855d36e1781d234129e0a8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
